CREATE OR REPLACE FORCE VIEW "SIGAT"."VISTA_CONDUCTORES" ("OBJECTID", "CODIGO_ACCIDENTADO", "CODIGO_ACCIDENTE", "CODIGO_VEHICULO", "CODIGO_VICTIMA", "PRIMER_APELLIDO", "SEGUNDO_APELLIDO", "NOMBRE", "FECHA_NACIMIENTO", "TIPO_IDENTIFICACION", "NUMERO_IDENTIFICACION", "DIRECCION", "CODIGO_MUNICIPIO", "TELEFONO", "CON_CINTURON", "CLINICA_ATENCION", "CON_CASCO", "CONDICION", "SEXO", "ESTADO", "GRAVEDAD_LESION", "MUERTE_POSTERIOR", "FECHA_CAMBIOGRAVEDAD", "DIAGNOSTICO_FALLECIMIENTO", "CLASE_OFICIAL", "GRADO_OFICIAL", "UNIDAD", "ENSERVICIO", "SINIDENTIFICACION", "DEPENDENCIA_OFICIAL", "CHALECO", "TRASLADADO", "NACIONALIDAD", "AUTORIZO", "EXAMEN") AS 
  SELECT 
  A.OBJECTID,
  A.CODIGO_ACCIDENTADO,
  A.CODIGO_ACCIDENTE,
  A.CODIGO_VEHICULO,
  A.CODIGO_VICTIMA,
  A.PRIMER_APELLIDO,
  A.SEGUNDO_APELLIDO,
  A.NOMBRE,
  A.FECHA_NACIMIENTO,
  A.TIPO_IDENTIFICACION,
  A.NUMERO_IDENTIFICACION,
  A.DIRECCION,
  A.CODIGO_MUNICIPIO,
  A.TELEFONO,
  A.CON_CINTURON,
  A.CLINICA_ATENCION,
  A.CON_CASCO,
  A.CONDICION,
  A.SEXO,
  A.ESTADO,
  A.GRAVEDAD_LESION,
  A.MUERTE_POSTERIOR,
  A.FECHA_CAMBIOGRAVEDAD,
  A.DIAGNOSTICO_FALLECIMIENTO,
  A.CLASE_OFICIAL,
  A.GRADO_OFICIAL,
  A.UNIDAD,
  A.ENSERVICIO,
  A.SINIDENTIFICACION,
  A.DEPENDENCIA_OFICIAL,
  A.CHALECO,
  A.TRASLADADO,
  A.NACIONALIDAD,
  A.AUTORIZO,
  A.EXAMEN
FROM VICTIMAS A 
WHERE CODIGO_VICTIMA = 0;
 

   COMMENT ON TABLE "SIGAT"."VISTA_CONDUCTORES"  IS 'Esta vista trae solo las victimas 0, las cuales corresponden a solo conductores.';
